# Generated by Django 2.0.8 on 2018-12-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181218_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/%y/%m/%d/'),
        ),
    ]
