# Generated by Django 2.0.8 on 2018-12-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181218_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='avatars/anonymous.png', upload_to='users/%y/%m/%d/'),
        ),
    ]
