# Generated by Django 2.0.8 on 2019-02-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_contact_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, default='backgrounds/background.jpg', upload_to='backgrounds'),
        ),
    ]
