# Generated by Django 2.0.8 on 2018-11-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(default='', max_length=254)),
                ('cusine_type', models.CharField(default='', max_length=254)),
                ('diet_type', models.CharField(default='', max_length=254)),
                ('ingredients', models.TextField()),
                ('preparation', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
