# Generated by Django 2.0.8 on 2018-11-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
