# Generated by Django 2.0.8 on 2018-11-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_videofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='videofile',
        ),
    ]
