# Generated by Django 2.0.8 on 2019-01-09 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0009_auto_20181213_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='recipes_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
