# Generated by Django 2.0.8 on 2019-02-03 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20190201_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recipes_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
